/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZQO55v1DbJX
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Baseline() {
  return (
    <main className="w-full py-6 space-y-6">
      <section className="w-full pt-6 pb-12 md:pt-12 md:pb-24">
        <div className="container flex flex-col items-center justify-center px-4 space-y-4 text-center md:space-y-8">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Hi, I’m Emily Parker</h1>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              I craft beautiful and intuitive user experiences. Turning complex problems into simple and elegant
              designs.
            </p>
          </div>
          <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center">
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-4 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
              href="#"
            >
              Download Resume
            </Link>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-4 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
              href="#"
            >
              Contact Me
            </Link>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:gap-8 md:px-6 lg:gap-10">
          <div className="space-y-4 md:space-y-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Case Studies</h2>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              A collection of my work and design process.
            </p>
          </div>
          <div className="grid w-full grid-cols-1 gap-4 md:grid-cols-2 md:gap-8">
            <div className="flex flex-col gap-2">
              <Link
                className="inline-flex flex-1 flex-col rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-transform hover:scale-105"
                href="#"
              >
                <img
                  alt="Cover image"
                  className="aspect-[4/3] object-cover object-center"
                  height="400"
                  src="/placeholder.svg"
                  width="600"
                />
                <div className="p-4 bg-gray-50 text-sm font-medium dark:bg-gray-800">Case Study One</div>
              </Link>
              <p className="text-sm text-gray-500 dark:text-gray-400">Description</p>
            </div>
            <div className="flex flex-col gap-2">
              <Link
                className="inline-flex flex-1 flex-col rounded-lg overflow-hidden shadow-md hover:shadow-lg transition-transform hover:scale-105"
                href="#"
              >
                <img
                  alt="Cover image"
                  className="aspect-[4/3] object-cover object-center"
                  height="400"
                  src="/placeholder.svg"
                  width="600"
                />
                <div className="p-4 bg-gray-50 text-sm font-medium dark:bg-gray-800">Case Study Two</div>
              </Link>
              <p className="text-sm text-gray-500 dark:text-gray-400">Description</p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:gap-8 md:px-6 lg:gap-10">
          <div className="space-y-4 md:space-y-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About Me</h2>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              I’m a passionate designer with a love for creating beautiful interfaces that are both elegant and
              user-friendly.
            </p>
          </div>
          <div className="grid w-full grid-cols-1 gap-4 md:grid-cols-2 md:gap-8">
            <div className="space-y-4">
              <h3 className="text-xl font-bold tracking-tight">Experience</h3>
              <ul className="grid w-full grid-cols-1 gap-2 text-sm md:grid-cols-1 md:text-base lg:gap-4">
                <li>Senior Product Designer at Acme Inc.</li>
                <li>Lead UX Designer at Beta Co.</li>
                <li>Freelance Designer at Studio 42</li>
              </ul>
            </div>
            <div className="space-y-4">
              <h3 className="text-xl font-bold tracking-tight">Skills</h3>
              <ul className="grid w-full grid-cols-1 gap-2 text-sm md:grid-cols-1 md:text-base lg:gap-4">
                <li>UI/UX Design</li>
                <li>Wireframing & Prototyping</li>
                <li>Design Thinking</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:gap-8 md:px-6 lg:gap-10">
          <div className="space-y-4 md:space-y-6">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Me</h2>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Ready to start a project? Drop me a message and I’ll get back to you as soon as possible.
            </p>
          </div>
          <form className="mx-auto max-w-sm space-y-4">
            <div className="grid grid-cols-1 gap-4">
              <Input placeholder="Name" type="text" />
              <Input placeholder="Email" type="email" />
              <Input placeholder="Subject" type="text" />
              <Textarea className="min-h-[150px]" placeholder="Your Message" />
            </div>
            <Button type="submit">Submit</Button>
          </form>
        </div>
      </section>
    </main>
  )
}
