/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w78UGy3ecaj
 */
import Link from "next/link"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Iteration1() {
  return (
    <>
      <div className="bg-gray-50/90 py-6">
        <div className="container flex items-center justify-center gap-4 px-4 text-center md:gap-10">
          <div className="space-y-1">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Jane Doe</h1>
            <p className="text-gray-500 md:text-xl/relaxed xl:text-base/relaxed dark:text-gray-400">UI/UX Designer</p>
          </div>
          <img
            alt="Jane Doe"
            className="rounded-full"
            height="160"
            src="/placeholder.svg"
            style={{
              aspectRatio: "160/160",
              objectFit: "cover",
            }}
            width="160"
          />
        </div>
      </div>
      <div className="bg-gray-900 py-12 md:py-24">
        <div className="container flex items-center justify-center gap-4 px-4 text-center md:gap-10">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-gray-50 dark:text-gray-950">
              Case Studies
            </h2>
            <p className="text-gray-300 md:text-xl/relaxed lg:text-base/relaxed dark:text-gray-400">
              Beautifully designed case studies.
            </p>
          </div>
        </div>
      </div>
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:gap-10">
        <div className="grid w-full grid-cols-1 items-stretch justify-center md:grid-cols-2 lg:gap-4 xl:gap-8">
          <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
            <Link
              className="inline-block w-full overflow-hidden rounded-lg shadow-lg translate-y-2 hover:translate-y-0 transition-transform"
              href="#"
            >
              <img
                alt="Project 1"
                className="aspect-[1.5] object-cover object-center"
                height="400"
                src="/placeholder.svg"
                width="600"
              />
              <div className="bg-gray-50 p-4 text-center dark:bg-gray-950">
                <h3 className="font-bold">Project 1</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Description of the project.</p>
              </div>
            </Link>
          </div>
          <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
            <Link
              className="inline-block w-full overflow-hidden rounded-lg shadow-lg translate-y-2 hover:translate-y-0 transition-transform"
              href="#"
            >
              <img
                alt="Project 2"
                className="aspect-[1.5] object-cover object-center"
                height="400"
                src="/placeholder.svg"
                width="600"
              />
              <div className="bg-gray-50 p-4 text-center dark:bg-gray-950">
                <h3 className="font-bold">Project 2</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Description of the project.</p>
              </div>
            </Link>
          </div>
        </div>
        <div className="grid w-full grid-cols-1 items-stretch justify-center md:grid-cols-2">
          <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
            <Link
              className="inline-block w-full overflow-hidden rounded-lg shadow-lg translate-y-2 hover:translate-y-0 transition-transform"
              href="#"
            >
              <img
                alt="Project 3"
                className="aspect-[1.5] object-cover object-center"
                height="400"
                src="/placeholder.svg"
                width="600"
              />
              <div className="bg-gray-50 p-4 text-center dark:bg-gray-950">
                <h3 className="font-bold">Project 3</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Description of the project.</p>
              </div>
            </Link>
          </div>
          <div className="mx-auto flex w-full items-center justify-center p-4 sm:p-8">
            <Link
              className="inline-block w-full overflow-hidden rounded-lg shadow-lg translate-y-2 hover:translate-y-0 transition-transform"
              href="#"
            >
              <img
                alt="Project 4"
                className="aspect-[1.5] object-cover object-center"
                height="400"
                src="/placeholder.svg"
                width="600"
              />
              <div className="bg-gray-50 p-4 text-center dark:bg-gray-950">
                <h3 className="font-bold">Project 4</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Description of the project.</p>
              </div>
            </Link>
          </div>
        </div>
      </div>
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About Me</h2>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Purus commodo massa tincidunt nunc pulvinar.
          </p>
        </div>
        <div className="mx-auto flex w-full max-w-sm flex-col items-center justify-center gap-4 p-4 md:max-w-none md:flex-row md:gap-10 lg:gap-4">
          <img
            alt="Jane Doe"
            className="rounded-full"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "200/200",
              objectFit: "cover",
            }}
            width="200"
          />
          <div className="space-y-4 text-left md:space-y-6">
            <div className="space-y-1.5">
              <h3 className="text-2xl font-bold tracking-tighter">Jane Doe</h3>
              <p className="text-gray-500 dark:text-gray-400">UI/UX Designer</p>
            </div>
            <div className="space-y-4">
              <p className="text-sm text-gray-500/70 md:text-base dark:text-gray-400/70">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Purus commodo massa tincidunt nunc pulvinar.
              </p>
            </div>
            <div className="grid gap-1.5">
              <Link
                className="inline-flex items-center text-sm font-medium underline transition-colors hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Read my blog
                <ChevronRightIcon className="w-4 h-4 ml-1.5 peer" />
              </Link>
            </div>
          </div>
        </div>
      </div>
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Me</h2>
          <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed dark:text-gray-400">
            Ready to start your next project? Let's connect.
          </p>
        </div>
        <div className="mx-auto max-w-[400px] space-y-4">
          <div className="grid grid-cols-1 gap-4">
            <div className="space-y-2">
              <Label className="text-base" htmlFor="name">
                Name
              </Label>
              <Input id="name" placeholder="Enter your name" />
            </div>
            <div className="space-y-2">
              <Label className="text-base" htmlFor="email">
                Email
              </Label>
              <Input id="email" placeholder="Enter your email" type="email" />
            </div>
            <div className="space-y-2">
              <Label className="text-base" htmlFor="message">
                Message
              </Label>
              <Textarea className="min-h-[100px] resize-y" id="message" placeholder="Enter your message" />
            </div>
          </div>
          <Button className="w-full h-10 justify-center md:w-[50%]">Let's connect</Button>
        </div>
      </div>
    </>
  )
}


function ChevronRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
