/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Cmus5GKCeeS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card"

export function Iteration6Projects() {
  return (
    <section className="w-full py-6">
      <div className="container mx-auto grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10"> 
        <div className="space-y-3 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Our Projects</h2> 
          <p className="mx-auto max-w-[600px] text-gray-500 md:text-lg/relaxed lg:text-base/relaxed xl:text-lg/relaxed dark:text-gray-400">
            Open source projects we maintain and contribute to.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:gap-12"> 
          <Card>
              <div className="aspect-[16/9] overflow-hidden rounded-xl">
                <img
                  alt="Cover image"
                  className="object-cover"
                  height="360"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "640/360",
                    objectFit: "cover",
                  }}
                  width="640"
                />
              </div>
              <CardContent className="p-0">
              <div className="grid gap-2">
                <h3 className="text-xl font-bold">Next.js</h3> 
                <p className="text-sm">The React Framework</p> 
              </div>
            </CardContent>
            </Card>
            <Card>
              <div className="aspect-[16/9] overflow-hidden rounded-xl">
                <img
                  alt="Cover image"
                  className="object-cover"
                  height="360"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "640/360",
                    objectFit: "cover",
                  }}
                  width="640"
                />
              </div>
              <CardContent className="p-0">
                <div className="grid gap-2">
                  <h3 className="text-xl font-bold">Vercel</h3>
                  <p className="text-sm">The best way to deploy your frontend</p>
                </div>
              </CardContent>
            </Card>
            <Card>
              <div className="aspect-[16/9] overflow-hidden rounded-xl">
                <img
                  alt="Cover image"
                  className="object-cover"
                  height="360"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "640/360",
                    objectFit: "cover",
                  }}
                  width="640"
                />
              </div>
              <CardContent className="p-0">
                <div className="grid gap-2">
                  <h3 className="text-xl font-bold">Shadcn</h3>
                  <p className="text-sm">The best way to build your frontend</p>
                </div>
              </CardContent>
            </Card>
        </div>
      </div>
    </section>
  )
}


