/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dc9TT9mUWs5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Iteration7NewGenProjects() {
  return (
    <section className="w-full py-12">
      <div className="container grid grid-cols-1 md:grid-cols-3 gap-6 items-start justify-items-center">
        <div className="relative group overflow-hidden rounded-lg">
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center p-4 gap-4 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
            <h3 className="font-semibold text-xl">Project 1</h3> 
            <p className="text-base text-gray-500 dark:text-gray-400">This is a brief description of project 1.</p>
          </div>
          <img
            alt="Project 1"
            className="object-cover w-full h-60"
            height={400}
            src="/placeholder.svg"
            style={{
              aspectRatio: "800/400",
              objectFit: "cover",
            }}
            width={800}
          />
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center p-4 gap-4 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
            <h3 className="font-semibold text-xl">Project 2</h3> 
            <p className="text-base text-gray-500 dark:text-gray-400">This is a brief description of project 2.</p>
          </div>
          <img
            alt="Project 2"
            className="object-cover w-full h-60"
            height={400}
            src="/placeholder.svg"
            style={{
              aspectRatio: "800/400",
              objectFit: "cover",
            }}
            width={800}
          />
        </div>
        <div className="relative group overflow-hidden rounded-lg">
          <div className="absolute inset-0 z-10 flex flex-col items-center justify-center p-4 gap-4 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
            <h3 className="font-semibold text-xl">Project 3</h3> 
            <p className="text-base text-gray-500 dark:text-gray-400">This is a brief description of project 3.</p>
          </div>
          <img
            alt="Project 3"
            className="object-cover w-full h-60"
            height={400}
            src="/placeholder.svg"
            style={{
              aspectRatio: "800/400",
              objectFit: "cover",
            }}
            width={800}
          />
        </div>
      </div>
    </section>
  )
}
