/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qtyAm1bdt3j
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Iteration6AboutMe() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container mx-auto flex flex-col items-center justify-center gap-4 px-4 md:gap-8 md:px-6"> 
        <div className="space-y-3 text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">About Me</h2> 
          <p className="text-gray-500 md:text-lg/relaxed xl:text-lg/relaxed dark:text-gray-400"> 
            I’m a passionate designer who loves creating beautiful and user-friendly interfaces.
          </p>
        </div>
        <div className="flex items-center gap-4 md:gap-8 lg:gap-12 flex-col lg:flex-row">
          <div className="rounded-full overflow-hidden border-4 border-white border-opacity-25 dark:border-opacity-50 w-36 h-36 md:w-44 md:h-44 flex items-center justify-center"> 
            <img
              alt="Picture of the author"
              className="w-full h-full rounded-full object-cover" 
              height="150"
              src="/placeholder.svg"
              style={{ aspectRatio: "150/150", objectFit: "cover" }}
              width="150"
            />
          </div>
          <div className="space-y-4"> 
            <div className="space-y-2 text-center md:text-left">
              <h3 className="text-2xl font-bold tracking-tight">Ryan Skelton</h3> 
              <p className="text-sm text-gray-500 tracking-wide dark:text-gray-400">UX Designer</p>
            </div>
            <div className="space-y-4 md:space-y-6">
              <p className="text-gray-600 max-w-prose md:text-lg/relaxed xl:text-base/relaxed dark:text-gray-400">
                I have over 10 years of experience designing digital products. My expertise includes user research,
                wireframing, and prototyping. I’m dedicated to creating designs that are both visually stunning and
                highly functional.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
