/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VQzIoLm03vx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Archivo } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Iteration7AboutMe() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 border-t last:border-0">
      <div className="container flex flex-col gap-4 px-4 md:px-6 mx-auto grid max-w-5xl items-center justify-items-center gap-6 lg:grid-cols-2 lg:gap-10">
        <div className="mx-auto grid max-w-5xl items-center gap-6 lg:grid-cols-2 lg:gap-10">
          <img
            alt="Avatar"
            className="mx-auto h-[200px] w-[200px] rounded-full border border-gray-200 aspect-square object-cover object-center dark:border-gray-800"
            
            src="/placeholder.svg"
            
          />
          <div className="space-y-4">
            <div className="space-y-2">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl">Jane Doe</h1>
              <p className="text-gray-500 dark:text-gray-400">UI/UX Designer</p>
            </div>
            <div className="space-y-4">
              <p className="text-gray-500 md:text-base/relaxed lg:text-xl/relaxed xl:text-base/relaxed dark:text-gray-400">
                Passionate about creating beautiful and intuitive user interfaces. I believe in the power of design to
                transform digital experiences. My goal is to make the complex simple and the ordinary extraordinary.
              </p>
              <Link
                className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-4 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                href="#"
              >
                Learn More
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
