/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Ur5zuUN9Wki
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Iteration7Hero() {
  return (
    <section className="w-full py-6 md:py-12 lg:py-16">
      <div className="container grid gap-6 px-4 md:px-6">
        <div className="flex flex-col items-center space-y-2 text-center">
          <div className="space-y-2">
            <div className="flex flex-col space-y-1">
              <span className="text-sm font-medium tracking-wider text-gray-500 uppercase dark:text-gray-400">
                Meet the
              </span>
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">Sarah Day</h1>
            </div>
            <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
              I design beautiful, user-friendly interfaces that make the web a better place.
            </p>
          </div>
          <img
            alt="Projects"
            className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom"
            height="250"
            src="/placeholder.svg"
            width="500"
          />
          <div className="flex justify-center">
            <Link
              className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
              href="#"
            >
              View Projects
            </Link>
          </div>
        </div>
      </div>
    </section>
  )
}
